//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localmarket_App.MultiIdiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrmPaginaComercioIng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrmPaginaComercioIng() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localmarket_App.MultiIdiomas.FrmPaginaComercioIng", typeof(FrmPaginaComercioIng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string ajustes {
            get {
                return ResourceManager.GetString("ajustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Out.
        /// </summary>
        internal static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Business.
        /// </summary>
        internal static string CrearEmpresa {
            get {
                return ResourceManager.GetString("CrearEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dark Mode.
        /// </summary>
        internal static string ModoNoche {
            get {
                return ResourceManager.GetString("ModoNoche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Business Page.
        /// </summary>
        internal static string PaginaComercio {
            get {
                return ResourceManager.GetString("PaginaComercio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Profile.
        /// </summary>
        internal static string PerfilUsuario {
            get {
                return ResourceManager.GetString("PerfilUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products/Services.
        /// </summary>
        internal static string ProductosServicios {
            get {
                return ResourceManager.GetString("ProductosServicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reviews.
        /// </summary>
        internal static string Reseñas {
            get {
                return ResourceManager.GetString("Reseñas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rating:.
        /// </summary>
        internal static string Valoracion {
            get {
                return ResourceManager.GetString("Valoracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location.
        /// </summary>
        internal static string VerUbi {
            get {
                return ResourceManager.GetString("VerUbi", resourceCulture);
            }
        }
    }
}
